[package]
name = "win-switch-rs"
version = "0.1.0"
authors = ["Adam Simpson <adam@heysparkbox.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddc-hi = "0.3.0"
mccs-db = "0.1.2"
argh = "0.1.4"
anyhow = "1.0.35"